### ISSUE TITLE
Doesn't compile on Zig 0.9.1

### ISSUE THREAD

**Issue by tinywombat765** [MasterQ32/gurl#5]
```
/home/zethra/Clones/gurl/lib/zig-bearssl/src/lib.zig:276:79: error: use of undeclared identifier 'Certificate'
    fn fromX509(allocator: *std.mem.Allocator, cert: *c.br_x509_certificate) !Certificate {
                                                                              ^
/home/zethra/Clones/gurl/lib/zig-bearssl/src/lib.zig:689:27: error: use of undeclared identifier 'c_void'
                @ptrCast(*c_void, in_stream),
                          ^
/home/zethra/Clones/gurl/lib/zig-bearssl/src/lib.zig:709:28: error: use of undeclared identifier 'c_void'
        fn sockRead(ctx: ?*c_void, buf: [*c]u8, len: usize) callconv(.C) c_int {
                           ^
/home/zethra/Clones/gurl/lib/zig-bearssl/src/lib.zig:717:29: error: use of undeclared identifier 'c_void'
        fn sockWrite(ctx: ?*c_void, buf: [*c]const u8, len: usize) callconv(.C) c_int {
                            ^
/home/zethra/Clones/gurl/lib/zig-bearssl/src/lib.zig:764:31: error: use of undeclared identifier 'c_void'
fn appendToBuffer(dest_ctx: ?*c_void, buf: ?*const c_void, len: usize) callconv(.C) void {
                              ^
/home/zethra/Clones/gurl/lib/zig-bearssl/src/lib.zig:820:30: error: unused function parameter
    fn encode(buffer: ?[]u8, value: Value) !usize {
```

**Comment by ikskuh** [comment]
Heya!

`gurl` needs a major rewrite and switch over to https://github.com/mattnite/zig-mbedtls to have a improved build situation. The code of `gurl` isn't maintained atm, but feel free to fork and improve!
